import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoryblokProvider from "@/ui/wrapper/storyblokProvider";
import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";
import ComponentMap from "@/ui/componentMap";

storyblokInit({
  accessToken: process.env.SB_ACCESS_TOKEN,
  use: [apiPlugin],
  apiOptions: {
    region: 'us',
  },
  components: ComponentMap,
});


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>

    </StoryblokProvider>
  );
}
